# 服务端口,因为这里配置了微信扫码登录，为了方便本地测试，在注册微信开发者时，域名中配置了跳转到本地的路径(端口与请求路径都要改)
server:
  port: 8150
#server.port=8006
# 服务名
spring:
  application:
    name: service-ucenter

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_education?serverTimezone=GMT%2B8
    username: root
    password: root

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  #redis连接
  redis:
    host: 192.168.233.129
    port: 6379
    database: 0
    timeout: 1800000

    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
        #最小空闲

  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  #开启熔断机制
feign:
  hystrix:
    enabled: true

# 设置hystrix超时时间，默认1000ms
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/lcc/educenter/mapper/xml/*.xml

  #mybatis日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 微信开放平台 appid
wx:
  open:
    app_id: wxed9954c01bb89b47
    # 微信开放平台 appsecret
    app_secret: a7482517235173ddb4083788de60b90e
    # 微信开放平台 重定向url
    redirect_url: http://guli.shop/api/ucenter/wx/callback